name: Create TCC File

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tcc-filipe-cancio.tex
          working_directory: monograph/
          continue_on_error: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: tcc-cancio
          path: monograph/tcc-filipe-cancio.pdf
