name: Create TCC File

on:
  push:
    branches: [ "main","feature_latex" ]
  pull_request:
    branches: [ "main","feature_latex" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tcc-filipe-cancio.tex
          working_directory: monograph/
          continue_on_error: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: tcc-cancio-${{ github.ref_name }}
          path: monograph/tcc-filipe-cancio.pdf
      - name: Upload Release Asset

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload v0 monograph/tcc-filipe-cancio.pdf
