name: Create TCC File

on:
  push:
    branches: [ "main","feature_latex" ]
  pull_request:
    branches: [ "main","feature_latex" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: monograph/
          continue_on_error: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: tcc-cancio-${{ github.ref_name }}
          path: monograph/main.pdf

      - name: Upload PDF file to release
        uses: softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: monograph/main.pdf
