name: Create TCC File

on:
  push:
    branches: [ "main","feature_latex" ]
  pull_request:
    branches: [ "main","feature_latex" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Github Action for LaTeX
        uses: Sakul6499/GitHub-Action-LaTeX@v1.0.0
        with:
          latex_main_file: a_PFC_main.tex
          working_directory: monograph/
          latex_compiler: latexmk
          latex_compiler_arguments: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode"

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf